# Network structure #
NN_HIDDEN_COUNT = 8

# Training #
LEARNING_RATE = 1e-4
TRAIN_ITERATIONS = 5000
REWARD_HISTORY_DISCOUNT = 0.99
UPDATE_FREQUENCY = 20
STEP_TIMEOUT = .3

# Printing #
PRINT_TIMEOUT_ITERATIONS = 100
